---
controller_credentials:
- name: github
  description: Credentials for GitHub
  organization: "{{ demo_organization_name }}"
  credential_type: Source Control

- name: gitlab
  description: Credentials for GitLab
  organization: "{{ demo_organization_name }}"
  credential_type: Source Control
  inputs:
    username: username
    password: password

- name: RHEL
  description: RHEL Credentials
  organization: "{{ demo_organization_name }}"
  credential_type: Machine
  inputs:
    username: root
    password: redhat
    become_method: sudo
...