---
controller_credentials:
  - name: github
    credential_type: Source Control
    organization: "{{ demo_organization_name }}"
    description: Github
  
  - name: gitlab
    description: Credentials for GitLab
    organization: "{{ demo_organization_name }}"
    credential_type: Source Control
    inputs:
      username: username
      password: password
...