---
controller_roles:

  - users:
      - breakglass-user
      - auditor
    target_team: "{{ demo_team_name }}"
    role: member

  # Create an admin user to manage the BreakGlass organization
  - user: breakglass-admin
    organization: "{{ demo_organization_name }}"
    roles:
      - admin

  - team: "{{ demo_team_name }}"
    organization: "{{ demo_organization_name }}"
    roles:
      - execute
      - read

...